apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app2
  namespace: app2
spec:
  values:
    resources:
      limits:
        cpu: 90m
        memory: 64Mi
      requests:
        cpu: 8m
        memory: 24Mi