apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
spec:
  values:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 24Mi