apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app2
spec:
  interval: 1m
  releaseName: app1
  chart:
    spec:
      chart: apps/charts/app2
      sourceRef:
        kind: GitRepository
        name: myrepo
  values:
    replicaCount: 2

    image:
      repository: ghcr.io/tkubica12/gitops-flux-arc/pod_hello
      tag: 1

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 32Mi