apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: repo-app2
spec:
  interval: 5m
  url: https://github.com/tkubica12/gitops-flux-arc
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include apps directory
    !/apps/