apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: app1
spec:
  values:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 60m
        memory: 64Mi