apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.0.6"
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer