name: TF apply
on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_dir: 
          - clusters/customer-01-prod/terraform
          - clusters/customer-01-staging/terraform
          - clusters/customer-02-prod/terraform
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
         
      - name: 'Terraform Init'
        working-directory: ${{ matrix.tf_dir }}
        run: |
          terraform init

      - name: 'Terraform Apply'
        working-directory: ${{ matrix.tf_dir }}
        run: terraform apply -auto-approve